/**
 * Prism3 engine — the fidelity report (docs/07 §11.3, Decision A).
 *
 * Given a standard `design.md` (the observed brand values), the classification,
 * and the generated theme, produce a full-parity Markdown report: the engine pins
 * the brand anchor exactly, GENERATES the rest, and reports where its generated
 * system DIVERGES from the observed values — across every axis (colour ΔE00,
 * typography, spacing, radius, elevation). Divergence is the point: the engine
 * does not trust extracted ramps as final (§11.3), so every deviation is surfaced
 * for a decision rather than hidden.
 *
 * Pure + brand-agnostic — no I/O, keyed on `std.name`. Used by `cli.ts --fidelity`.
 */
import { RGB, contrast, deltaE2000, hexToRgb } from './color';
import { Step } from './ramp';
import { BrandInput, PaletteBuild, Theme } from './theme';
import { StandardDesignMd } from './standard-design-md';
import { ColorClassification, ProvidedColor } from './classify-colors';

const de2 = (n: number) => n.toFixed(2);
const nearestStep = (pal: PaletteBuild | undefined, rgb: RGB): { step: Step; de: number } | null => {
  if (!pal || !pal.steps.length) return null;
  let best = pal.steps[0], bestDe = Infinity;
  for (const s of pal.steps) { const d = deltaE2000(s.rgb, rgb); if (d < bestDe) { bestDe = d; best = s; } }
  return { step: best, de: bestDe };
};
const palByName = (theme: Theme, name: string | null) => theme.palettes.find((p) => p.palette === name);

// observed type-tier → engine type group (the vocabulary alignment finding).
const TIER_TO_GROUP: Record<string, string> = {
  mega: 'display', display: 'display', title: 'title', button: 'label',
  body: 'body', caption: 'caption', label: 'label', eyebrow: 'eyebrow', code: 'code',
};
const tierOf = (token: string) => token.toLowerCase().split('-')[0];
const pxNum = (v: string | number | undefined): number | null => {
  if (v == null) return null;
  const m = String(v).match(/-?\d*\.?\d+/);
  return m ? Number(m[0]) : null;
};

export type FidelityStats = { resolved: number; aliases: number; modePass: number; modeChecks: number };

/** Build the full-parity fidelity report. Returns the Markdown + the anchor ΔE00
 *  (the headline exact-anchor-preservation number, for a caller gate). */
export const buildFidelityReport = (std: StandardDesignMd, cls: ColorClassification, input: BrandInput, theme: Theme,
                                    stats: FidelityStats, xApplied: string[]): { md: string; anchorDe: number } => {
  const md: string[] = [];
  const P = (...l: string[]) => md.push(...l);
  const brand = std.name;

  P(`# ${brand} — Prism3 fidelity report`, '',
    `> Generated by the Prism3 CLI (\`cli.ts <design.md> --fidelity\`, docs/07 §11). A real \`brand-skills\``,
    `> \`design.md\` run through the engine: the brand anchor is **pinned exactly**, the rest is **generated +`,
    `> contrast-verified**, and every **observed** value is diffed against the engine's generated system`,
    `> (Decision A, §11.3). Divergence is the point — the engine does not trust extracted ramps as final.`, '');

  // headline
  const primaryPal = palByName(theme, 'primary')!;
  const anchor = nearestStep(primaryPal, hexToRgb(std.colors.primary))!;
  const pOnWhite = contrast(hexToRgb(std.colors.primary), { r: 255, g: 255, b: 255 });
  P(`## Headline`, '',
    `- **Anchor reproduction** — provided \`primary\` \`${std.colors.primary}\` vs generated \`primary.${anchor.step.key}\` \`${anchor.step.hex}\`: **ΔE00 ${de2(anchor.de)}** (≈0 confirms exact-anchor preservation).`,
    `- **Aliases**: ${stats.resolved}/${stats.aliases} resolve · **mode contrast contracts**: ${stats.modePass}/${stats.modeChecks} hold.`,
    `- **\`primary\` on white**: the engine measures **${de2(pOnWhite)}:1** (${pOnWhite >= 4.5 ? 'clears' : 'below'} small-text AA). The engine measures every contract, so if the brief's prose states a different figure, the *measured* value governs — a stale contrast claim in the source can't propagate.`,
    `- Palettes generated: ${theme.palettes.map((p) => p.palette).join(', ')} · danger draws from \`${theme.roleToPalette.danger}\`.`,
    `- x-prism3 levers: ${xApplied.length ? xApplied.join(', ') : 'none (plain spec → engine defaults)'}.`, '');

  // §1 colour
  P(`## 1. Colour fidelity (ΔE00 — observed swatch vs nearest generated step)`, '');
  const groups: { title: string; filter: (p: ProvidedColor) => boolean }[] = [
    { title: 'Primary (brand anchor + state variants)', filter: (p) => p.baseRamp === 'primary' },
    { title: 'Secondary', filter: (p) => p.baseRamp === 'secondary' },
    { title: 'Tertiary', filter: (p) => p.baseRamp === 'tertiary' },
    { title: 'Neutral (+ white)', filter: (p) => p.baseRamp === 'neutral' },
    { title: 'Status: success / warning / danger(←error)', filter: (p) => ['success', 'warning', 'danger'].includes(p.baseRamp ?? '') },
    { title: 'Info (engine-synthesised — expect divergence)', filter: (p) => p.baseRamp === 'info' },
  ];
  // How each observed swatch relates to the generated ramp: brand palettes pin an
  // EXACT step; neutral swatches DERIVE the aggregate { hue, chroma }; status pins
  // HUE + chroma (lightness placed by the ramp); the rest are regenerated + diffed.
  const anchorLabel = (p: ProvidedColor): string =>
    p.role === 'primary' || p.role === 'secondary' || p.role === 'tertiary' ? '✅ pinned (exact step)'
      : p.role === 'neutral' ? 'derived (→ hue/chroma)'
      : p.role === 'success' || p.role === 'warning' || p.role === 'error' ? 'hue-pinned (L by ramp)'
      : '·';
  const allDe: number[] = [];
  for (const g of groups) {
    const rows = cls.provided.filter(g.filter);
    if (!rows.length) continue;
    P(`### ${g.title}`, '', '| token | observed | → nearest generated | ΔE00 | relation |', '|---|---|---|---|---|');
    for (const p of rows) {
      const n = nearestStep(palByName(theme, p.baseRamp), p.rgb);
      if (n) allDe.push(n.de);
      P(`| \`${p.token}\` | ${p.hex} | ${n ? `\`${p.baseRamp}.${n.step.key}\` ${n.step.hex}` : '—'} | ${n ? de2(n.de) : '—'} | ${anchorLabel(p)} |`);
    }
    P('');
  }
  const meanDe = allDe.reduce((a, b) => a + b, 0) / (allDe.length || 1);
  P(`**Aggregate colour ΔE00** across ${allDe.length} observed swatches: **${de2(meanDe)}** (the anchor pins to ~0; the ramp steps and status/neutral — which the engine PLACES by contrast role, not by the observed value — carry the divergence).`, '');

  // §2 typography
  P(`## 2. Typography parity`, '',
    `Observed type roles are mapped onto the engine's semantic vocabulary (\`display\` / \`title\` / \`body\` /`,
    `\`label\` / \`caption\` / \`eyebrow\` / \`code\`) — \`mega-*\`→\`display\` (top rungs), \`button-*\`→\`label\` (§11.5).`, '',
    '| observed token | family · size · weight | → engine group | nearest engine composite | Δsize |', '|---|---|---|---|---|');
  const comps = theme.typography.composites;
  const famStack = (role: string) => theme.typography.families.find((f) => f.role === role)?.stack[0] ?? role;
  for (const [token, tok] of Object.entries(std.typography)) {
    const group = TIER_TO_GROUP[tierOf(token)] ?? '—';
    const size = pxNum(tok.fontSize);
    const cands = comps.filter((c) => c.group === group);
    let near = cands[0], best = Infinity;
    for (const c of cands) { const d = size != null ? Math.abs(c.sizePx - size) : 0; if (d < best) { best = d; near = c; } }
    const engFam = near ? famStack(near.family) : '—';
    const dSize = near && size != null ? near.sizePx - size : null;
    P(`| \`${token}\` | ${tok.fontFamily} · ${tok.fontSize} · ${tok.fontWeight} | \`${group}\` | ${near ? `\`${near.path}\` (${near.sizePx}px, ${engFam}, w:${near.weightRole})` : '—'} | ${dSize == null ? '—' : (dSize > 0 ? '+' : '') + dSize + 'px'} |`);
  }
  P('',
    `- **Weight naming differs:** observed uses numerics (e.g. 900/700/400); the engine uses function-named weight roles (subtle/default/emphasis/strong) over a numeric reference tier — a mapping, not a conflict.`,
    `- **Size ladder differs by design:** the engine ships a curated rem ladder, not the brand's exact px, so Δsize is expected; the families (\`${famStack('display')}\` / \`${famStack('text')}\`) round-trip.`, '');

  // §3 spacing
  P(`## 3. Spacing parity`, '',
    `Observed spacing (often a t-shirt scale) vs the engine's numbered-multiplier \`space\` scale on an 8px rhythm`,
    `(a deliberate, white-label-honest taxonomy — docs/00). Matched by px value:`, '',
    '| observed | px | engine token(s) at same px | note |', '|---|---|---|---|');
  for (const [token, val] of Object.entries(std.spacing)) {
    const px = pxNum(val);
    const hit = px != null ? theme.dims.space.filter((s) => s.px === px).map((s) => `space.${s.key}`) : [];
    P(`| \`${token}\` | ${px ?? '—'} | ${hit.length ? hit.join(', ') : '—'} | ${hit.length ? 'value present in engine scale' : 'not on the 8px-rhythm ladder'} |`);
  }
  P('', `- Taxonomy divergence is intentional (t-shirt→numbered); the engine covers most observed px, with off-rhythm values absent by design. A documented translation, not an alignment change.`, '');

  // §4 radius
  P(`## 4. Radius parity`, '',
    `Observed radius vs the engine's small **bounded** set (\`none/sm/md/lg/round\`) — radius is genuinely semantic (docs/00). Matched by px:`, '',
    '| observed | px | engine token at same px | note |', '|---|---|---|---|');
  for (const [token, val] of Object.entries(std.rounded)) {
    const px = pxNum(val);
    const hit = px != null ? theme.dims.radius.filter((r) => r.px === px).map((r) => `radius.${r.name}`) : [];
    P(`| \`${token}\` | ${px ?? '—'} | ${hit.length ? hit.join(', ') : '—'} | ${hit.length ? 'match' : 'no bounded-set equivalent'} |`);
  }
  P('', `- Engine radius (\`${theme.dims.radius.map((r) => `${r.name}=${r.px}`).join(', ')}\`) at scale ${theme.dims.radiusScaleValue}. To shift the form factor, set \`radiusScale\` in the \`x-prism3\` block (e.g. \`2\` for softer corners).`, '');

  // §5 elevation
  P(`## 5. Elevation parity`, '',
    `Observed elevation is single-layer CSS \`box-shadow\` strings; the engine generates a 6-step (\`xs–2xl\`) **two-layer**`,
    `(key + ambient) mode-aware ramp with a tinted-near-black colour. Different shapes — reported qualitatively:`, '',
    '| observed | value | nearest engine step (light, key blur / ambient blur) |', '|---|---|---|');
  const engSteps = theme.shadow.steps.filter((s) => s.name !== 'inset');
  for (const [token, val] of Object.entries(std.elevation)) {
    if (String(val).trim() === 'none') { P(`| \`${token}\` | none | \`flat\` (no shadow — engine composes a foreground tier + border) |`); continue; }
    const nums = String(val).replace(/rgba?\([^)]*\)/g, '').match(/-?\d*\.?\d+/g)?.map(Number) ?? [];
    const blur = nums[2] ?? 0;
    let near = engSteps[0], best = Infinity;
    for (const s of engSteps) { const d = Math.abs((s.light[0]?.blur ?? 0) - blur); if (d < best) { best = d; near = s; } }
    P(`| \`${token}\` | \`${val}\` | \`${near.name}\` (${near.light[0]?.blur ?? 0} / ${near.light[1]?.blur ?? 0}) |`);
  }
  P('', `- **Format divergence:** observed = one-layer CSS; engine = two-layer composite → Figma Effect Style, reduced in dark (lift-primary). A translation the exporter owns, not a like-for-like port.`, '');

  // §6 classification / decisions
  P(`## 6. Classification & engine decisions`, '');
  P(`### Colour-role classification log`, '', '| token | decision |', '|---|---|');
  for (const e of cls.log) P(`| \`${e.token}\` | ${e.decision} |`);
  P('');
  P(`### Engine decisions (from theme notes)`, '');
  for (const n of theme.notes) P(`- ${n}`);
  P('');
  P(`### Interchange notes`, '',
    `- **Colour-role classifier** reads \`primary/secondary/tertiary/neutral-<step>/success/warning/error/info\` by convention; \`error\`→\`danger\` is the one rename the engine applies (its status role is \`danger\`).`,
    `- **Scale/state variants** (\`*-dark\`, \`*-50\`, …) are observed ramp points; the engine regenerates the full ramp and reports divergence rather than consuming them.`,
    (std.colors.info && std.colors.secondary && std.colors.info.toLowerCase() === std.colors.secondary.toLowerCase()
      ? `- Observed \`info\` duplicates \`secondary\` (both \`${std.colors.info}\`); the engine synthesises \`info\` independently, so the dup doesn't propagate.` : ''),
    `- **\`x-prism3\`** carries engine-only levers (radiusScale, typeScale, density, motionTempo, actionPalette, iconContrast, surfaces, gradients). ${xApplied.length ? `Applied here: ${xApplied.join(', ')}.` : 'None here → engine defaults (the plain-spec guarantee).'}`, '');

  return { md: md.filter((l) => l !== undefined).join('\n') + '\n', anchorDe: anchor.de };
};
