/**
 * Prism3 engine — New Balance regression run.
 *
 * Generates NB's color ramps from the reverse-engineered schema and diffs
 * them against the actual hand-built NB tokens. This turns docs/02 (a paper
 * regression) into a real measurement. Run:  npx tsx Prism3/engine/nb-regression.ts
 *
 * The bar is perceptual + functional, never hex equality (docs/02 §1):
 *  - per-step CIEDE2000 against the real ramp
 *  - WCAG contrast contracts preserved
 *  - the 5 tonal bands map cleanly
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { RGB, contrast, deltaE2000 } from './color';
import { stepKey, autoPlaceStep, Step } from './ramp';
import { buildRamp } from './theme';
import { loadSpecs, nbTheme } from './nb-fixture';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../..');
const NB = resolve(repo, 'Tokens/New Balance/tokens/tokens/shared/core-color.json');

const WHITE: RGB = { r: 255, g: 255, b: 255 };
const BLACK: RGB = { r: 0, g: 0, b: 0 };

// ---- regression GATE thresholds (CR-06: this run must be able to FAIL) ----
// Every compared step must stay within the perceptual bar, EXCEPT the enumerated NB
// hand-authoring divergences (docs/02 §4) — steps where NB was hand-nudged and the engine
// deliberately does not reproduce the kink. Each outlier carries its OWN ceiling, so a NEW
// regression there still trips the gate; this replaces the old static prose that would have
// kept printing "known kink" over a fresh engine bug with the same signature. A per-step
// ceiling (not a mean-of-means) means one catastrophic step can no longer hide under a good
// aggregate; the covered-count assertion catches a truncated/renamed fixture (→ NaN mean).
const PER_STEP_CEILING = 3.5;                    // ΔE00 bar for every non-hand-nudged step
const KNOWN_OUTLIERS: Record<string, number> = { // NB hand-nudges: `${palette}.${stepKey}` → max ΔE00
  'red.050': 4.7, 'red.100': 5.5, 'red.300': 7.7, 'red.900': 4.3, 'red.950': 5.1, 'amber.600': 9.8,
};
const EXPECTED_STEPS_PER_SPEC = 20;              // NB ships 20 steps/palette — fewer = truncated/renamed
const failures: string[] = [];                  // any entry → non-zero exit at the end

// ---- load real NB palettes ----
const nb = JSON.parse(readFileSync(NB, 'utf8')).nbds.color as Record<string, any>;
const parseRgb = (s: string): RGB => {
  const [r, g, b] = s.match(/\d+/g)!.map(Number);
  return { r, g, b };
};
const nbStep = (pal: string, num: number): RGB | null => {
  const node = nb[pal]?.[stepKey(num)];
  return node?.$value ? parseRgb(node.$value) : null;
};

// ---- ramp specs (shared loader) ----
const specs = loadSpecs();

const out: string[] = [];
const p = (s = '') => { out.push(s); console.log(s); };

p('# NB Regression — engine output vs hand-built tokens');
p('');
p(`Generated by \`Prism3/engine/nb-regression.ts\`. Engine L defaults: lMax=0.975, lMin=0.16.`);
p('Diff metric: CIEDE2000 (ΔE00) generated-vs-actual per step. Target ≤ ~3 at consumed steps.');
p('');

let worstStep = { name: '', key: '', de: 0 };
const summary: { name: string; mean: number; max: number; maxKey: string; covered: number; within: number }[] = [];

for (const spec of specs) {
  const ramp = buildRamp(spec);
  p(`## ${spec.name}`);
  if (spec.anchor) {
    const auto = autoPlaceStep(spec.anchor.oklch.l);
    p(`Anchor pinned at \`${stepKey(spec.anchor.stepNum)}\` (exact). An even-L engine would auto-place this lightness at \`${stepKey(auto)}\`${auto !== spec.anchor.stepNum ? ` — a ${Math.abs(auto - spec.anchor.stepNum)}-unit placement gap, an NB ramp-evenness tell.` : ' — same step.'}`);
  }
  p('');
  p('| step | band | gen hex | NB hex | ΔE00 |');
  p('|---|---|---|---|---|');
  const des: number[] = [];
  let max = 0, maxKey = '';
  for (const s of ramp) {
    const actual = nbStep(spec.palette, s.num);
    if (!actual) continue;
    const de = deltaE2000(s.rgb, actual);
    des.push(de);
    if (de > max) { max = de; maxKey = s.key; }
    if (de > worstStep.de) worstStep = { name: spec.name, key: s.key, de };
    const ceiling = KNOWN_OUTLIERS[`${spec.palette}.${s.key}`] ?? PER_STEP_CEILING;
    if (de > ceiling) failures.push(`ΔE00 ${spec.palette}.${s.key} = ${de.toFixed(2)} exceeds ceiling ${ceiling} (${KNOWN_OUTLIERS[`${spec.palette}.${s.key}`] != null ? 'known-outlier allowance' : 'per-step bar'})`);
    const flag = de > 3 ? ' ⚠️' : '';
    p(`| ${s.key} | ${bandLabel(s.band)} | \`${s.hex}\` | \`${hexOf(actual)}\` | ${de.toFixed(2)}${flag} |`);
  }
  const mean = des.reduce((a, b) => a + b, 0) / des.length;
  const within = des.filter((d) => d <= 3).length;
  if (des.length !== EXPECTED_STEPS_PER_SPEC)
    failures.push(`${spec.name} (${spec.palette}): compared ${des.length} steps, expected ${EXPECTED_STEPS_PER_SPEC} — truncated or renamed NB fixture (a shrunk denominator silently passes a mean-of-means).`);
  summary.push({ name: spec.name, mean, max, maxKey, covered: des.length, within });
  p('');
  p(`**ΔE00 mean ${mean.toFixed(2)}, max ${max.toFixed(2)} at ${maxKey}** over ${des.length} steps.`);
  p('');
}

// ---- functional checks: tonal-band contrast contracts (§5.2) ----
p('## Tonal-band contrast contracts (generated ramps)');
p('');
// Look up by palette, not position (L-12) — a spec-order change must not silently point the
// contract gate at the wrong ramp.
const rampByPalette = (pal: string): Step[] => {
  const sp = specs.find((s) => s.palette === pal);
  if (!sp) throw new Error(`nb-regression: no spec for palette '${pal}' (have: ${specs.map((s) => s.palette).join(', ')})`);
  return buildRamp(sp);
};
const red = rampByPalette('red');
const neutral = rampByPalette('neutral');
const rgbAt = (r: Step[], n: number) => r.find((s) => s.num === n)!.rgb;

const checks: { label: string; got: number; pass: boolean; rule: string }[] = [];
const add = (label: string, got: number, pass: boolean, rule: string) =>
  checks.push({ label, got, pass, rule });

// Mid-Tone 500: AA (4.5) on white AND black
add('red.500 vs white', contrast(rgbAt(red, 500), WHITE), contrast(rgbAt(red, 500), WHITE) >= 4.5, '≥4.5 (Mid-Tone floor)');
add('red.500 vs black', contrast(rgbAt(red, 500), BLACK), contrast(rgbAt(red, 500), BLACK) >= 4.5, '≥4.5 (Mid-Tone floor)');
// 550 on Highlights
for (const hl of [25, 50]) {
  const c = contrast(rgbAt(red, 550), rgbAt(neutral, hl));
  add(`red.550 vs neutral.${stepKey(hl)}`, c, c >= 4.5, '≥4.5 (550 on Highlights)');
}
const c550w = contrast(rgbAt(red, 550), WHITE);
add('red.550 vs white', c550w, c550w >= 4.5, '≥4.5 (NB promo text canary)');
// ¼-Tones must NOT be text-safe on white (they are borders, §5.2)
for (const q of [100, 250, 350]) {
  const c = contrast(rgbAt(neutral, q), WHITE);
  add(`neutral.${stepKey(q)} vs white`, c, c < 4.5, '<4.5 (¼-Tone = borders, not text)');
}
// ¾-Tones / Shadows must be text-safe on white
for (const t of [650, 800, 950]) {
  const c = contrast(rgbAt(neutral, t), WHITE);
  add(`neutral.${stepKey(t)} vs white`, c, c >= 4.5, '≥4.5 (text on light)');
}

p('| check | ratio | rule | result |');
p('|---|---|---|---|');
for (const c of checks) p(`| ${c.label} | ${c.got.toFixed(2)} | ${c.rule} | ${c.pass ? '✅' : '❌'} |`);
p('');

// ---- compare the canary against the REAL NB value ----
const nbPromo = nbStep('red', 550)!;
p(`Canary cross-check — white on **real** NB \`red.550\`: ${contrast(nbPromo, WHITE).toFixed(2)}:1; on **generated** red.550: ${c550w.toFixed(2)}:1.`);
p('');

// ---- dimension axis regression (integer px → EXACT equality, not ΔE) ----
// NB is a fidelity TEST, not the taxonomy authority. On naming we deliberately
// followed Prism2 (numbered-multiplier space, KB POV 02/22), not NB's legacy
// t-shirt ramp — so SPACE validates against Prism2; RADIUS (which both systems
// name the same way) still validates against NB.
const PRISM2SPACE = resolve(repo, 'Tokens/Prism2/tokens/tokens/shared/space-size.json');
const NBRAD = resolve(repo, 'Tokens/New Balance/tokens/tokens/shared/radius.json');
const p2Space = JSON.parse(readFileSync(PRISM2SPACE, 'utf8')).nbds.pds.space as Record<string, any>;
const nbRad = JSON.parse(readFileSync(NBRAD, 'utf8')).nbds.radius as Record<string, any>;
const aliasPx = (v: string) => Number(v.match(/dimension\.(\d+)/)![1]);
const dims = nbTheme().dims;

p('## Dimension axis — generated vs hand-built (exact)');
p('');
p('Integer px, so the bar is **exact equality**, not ΔE. Space follows Prism2\'s numbered-multiplier scale (our adopted taxonomy — see naming POV); radius follows NB. Both fall out of two inputs: `spaceBase=8` and `radius.scale=1`.');
p('');
p('| token | kind | target | generated | actual | match |');
p('|---|---|---|---|---|---|');
let dimChecks = 0, dimPass = 0;
for (const s of dims.space) {
  const av = p2Space[s.key] ? aliasPx(p2Space[s.key].$value) : null;
  if (av == null) {
    // Defensive: a step the engine emits that Prism2 has no equivalent for would be
    // an intentional extension — shown for transparency, not counted against the
    // exact-match denominator. (Currently none: the engine reproduces all 18 keys.)
    p(`| space.${s.key} | space | — | ${s.px} | (engine addition) | ⊕ |`);
    continue;
  }
  dimChecks++; const okMatch = av === s.px; if (okMatch) dimPass++;
  p(`| space.${s.key} | space | Prism2 | ${s.px} | ${av} | ${okMatch ? '✅' : '❌'} |`);
}
for (const r of dims.radius) {
  const av = nbRad[r.name] ? aliasPx(nbRad[r.name].$value) : null;
  if (av == null) continue;
  dimChecks++; const okMatch = av === r.px; if (okMatch) dimPass++;
  p(`| radius.${r.name} | radius | NB | ${r.px} | ${av} | ${okMatch ? '✅' : '❌'} |`);
}
p('');
p(`**Dimension axis: ${dimPass}/${dimChecks} exact matches** — Prism2's full numbered space scale + NB's radius ramp, both generated from the engine's two dimension levers.`);
p('');

// ---- verdict ----
p('## Verdict');
p('');
const failed = checks.filter((c) => !c.pass);
const meanOfMeans = summary.reduce((a, s) => a + s.mean, 0) / summary.length;
// Fold the functional checks into the gate accumulator (they were report-only before CR-06).
for (const f of failed) failures.push(`contrast contract failed: ${f.label} = ${f.got.toFixed(2)} (rule ${f.rule})`);
if (dimPass !== dimChecks) failures.push(`dimension axis: ${dimPass}/${dimChecks} exact — a px lever drifted from Prism2 space / NB radius`);
for (const s of summary) p(`- **${s.name}** — ΔE00 mean ${s.mean.toFixed(2)}, max ${s.max.toFixed(2)} (${s.maxKey}), within-tolerance ${s.within}/${s.covered}.`);
p('');
p(`- Aggregate ΔE00 mean across ramps: **${meanOfMeans.toFixed(2)}**.`);
p(`- Worst step overall: **${worstStep.name} ${worstStep.key}** at ΔE00 ${worstStep.de.toFixed(2)} (an NB hand-applied hue kink — see docs/02 §4; enumerated in KNOWN_OUTLIERS with its own ceiling).`);
p(`- Contrast contracts: **${checks.length - failed.length}/${checks.length} pass**${failed.length ? ` — failing: ${failed.map((f) => f.label).join(', ')}` : '.'}`);
p(`- Dimension axis (Prism2 space + NB radius): **${dimPass}/${dimChecks} exact matches**.`);
p('');
// ---- the gate: per-step ΔE ceilings + covered-count + contracts + dims → non-zero exit ----
if (failures.length === 0) {
  p(`> ✅ **NB regression PASS.** Every step within its ΔE00 ceiling (${PER_STEP_CEILING} bar; ${Object.keys(KNOWN_OUTLIERS).length} enumerated NB hand-nudges within their allowances), all ${summary.length}×${EXPECTED_STEPS_PER_SPEC} steps compared, ${checks.length}/${checks.length} contrast contracts, ${dimPass}/${dimChecks} dimensions. Aggregate mean ΔE00 ${meanOfMeans.toFixed(2)}. The engine reproduces NB perceptually from the schema alone; the enumerated outliers are NB hand-authoring the schema intentionally resists, not engine error.`);
} else {
  p(`> ❌ **NB regression FAIL** — ${failures.length} issue(s) (exit 1). A per-step ceiling / covered-count / contract / dimension check tripped — this is a real fidelity regression, not a report note:`);
  for (const f of failures) p(`>   - ${f}`);
  process.exitCode = 1;
}
p('');
p('**Engine status:** contrast-role-targeted L placement is implemented — the Mid-Tone 500 is placed at the dual-side AA luminance pivot, so all band contrast contracts pass. NB hand-authoring divergences are enumerated in `KNOWN_OUTLIERS` (each with a ceiling), so a NEW regression at those steps still fails the gate rather than being waved through as a "known kink". Modes (light/dark/HC) and DTCG emit are also implemented.');

const reportPath = resolve(here, 'nb-regression-report.md');
writeFileSync(reportPath, out.join('\n') + '\n');
console.log(`\n[written] ${reportPath}`);

// helpers
function hexOf(rgb: RGB): string {
  return '#' + [rgb.r, rgb.g, rgb.b].map((v) => v.toString(16).padStart(2, '0')).join('');
}
function bandLabel(b: string): string {
  return ({ Highlights: 'Highlight', Quarter: '¼', Mid: 'Mid', ThreeQuarter: '¾', Shadows: 'Shadow' } as Record<string, string>)[b] ?? b;
}
